### PR TITLE
merge

### PR DESCRIPTION
**Pull request by bluenazgul**
merge

### CODE REVIEW

**Comment by japangelo-code** [comment]
@bluenazgul Hi I recently discovered this project and I was wondering if you happen to know the Germany SkyQ bouquet and subbouquet. I know the endpoint for their lineup is /as/services/{bouquet}/{subbouquet} so I was hoping you can help me with that. Thank you

**Comment by bluenazgul** [comment]
Iam the wrong Person for this Project, the Project owner is @RogerSelwyn please ask in His Repo - also i dont longer have an Sky Abo

**Comment by RogerSelwyn** [comment]
I don’t have a sky box anymore. That said if you follow through the code in the library you should be able to see where those properties are retrieved from on the box abs query them yourself.

**Comment by japangelo-code** [comment]
oh shoot..thats ok thank you guys :)

**Pull request merged**
